tor-address:
  name: Network Tor Address
  description: The Tor address for the network interface.
  type: pointer
  subtype: package
  package-id: squeakroad
  target: tor-address
  interface: main
lan-address:
  name: Network LAN Address
  description: The LAN address for the network interface.
  type: pointer
  subtype: package
  package-id: squeakroad
  target: lan-address
  interface: main
password:
  type: string
  name: Password
  description: Administrator password for Squeak Road (The username is 'squeakroad-admin')
  nullable: false
  copyable: true
  masked: true
  default:
    charset: "a-z,A-Z,0-9"
    len: 22
